// take key from url query string
const POKEMON_SHOWDOWN_TESTCLIENT_KEY = process.env.POKEMON_SHOWDOWN_TESTCLIENT_KEY;

console.log('Using POKEMON_SHOWDOWN_TESTCLIENT_KEY:', POKEMON_SHOWDOWN_TESTCLIENT_KEY);
